### ISSUE TITLE
Error while validating (Frequency mismatch)

### ISSUE THREAD

**Issue by JoshuaEbenezer** [dhytxz/ov7670_VDMA_VGA#1]
Hi I am getting the following error at the validation stage when I try to run your design :
[BD 41-237] Bus Interface property FREQ_HZ does not match between /ov7670_decode_stream/S00_AXI(100000000) and /axi_clock_converter_0/M_AXI(10000000).

I looked up the error on the Xilinx forums but was not able to change the frequency parameter for either of the clocks (they are read-only). Do you know how to fix this?

**Comment by Madesh12** [comment]
May I know which version you are using?
If it is latest version how did you update it from 2015.4?

**Comment by Madesh12** [comment]
Hi I am getting the following error at the validation stage when I try to run your design :
[BD 41-237] Bus Interface property FREQ_HZ does not match between /ov7670_decode_stream/S00_AXI(100000000) and /axi_clock_converter_0/M_AXI(10000000).

reply: Initially I also get the same error. After that I download the same project and run it fully without any interruption. Now that error is not coming

**Comment by JoshuaEbenezer** [comment]
Thanks. This was one year ago so I don't remember exactly but I think downloading the 2017 version fixed it for me.
